import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { AuthProvider } from "@/providers/auth";
import { FoodItemProvider } from "@/providers/foodItem";
import React from "react";
import { ClientManagementProvider } from "@/providers/clientManagement";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthProvider>
        <ClientManagementProvider>
          <FoodItemProvider>
            <body className={`${geistSans.variable} ${geistMono.variable}`}>
              {children}
            </body>
          </FoodItemProvider>
        </ClientManagementProvider>
      </AuthProvider>
    </html>
  );
}
