import type { Metadata } from "next";
import { AuthProvider } from "@/providers/auth";
import { FoodItemProvider } from "@/providers/foodItem";
import React from "react";
import { ClientManagementProvider } from "@/providers/clientManagement";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthProvider>
        <ClientManagementProvider>
          <FoodItemProvider>
            <body style={{padding: 0, margin: 0}}>
              {children}
            </body>
          </FoodItemProvider>
        </ClientManagementProvider>
      </AuthProvider>
    </html>
  );
}
